title: Singapore Institute of Retail Studies
title-abbreviated: NYP-SIRS
description: >- # this means to ignore newlines until "baseurl:"
  Description
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Resource Room and Pagination
paginate: 12

# Homepage sections
homepage_hero_i_want_to: false
homepage_resources: true

# Feedback Form URL
feedback_form_url: "https://form.sg/#!/forms/govtech/5a9ce876b3a3b6006e6b8335"

# FAQ URL
faq_url: "/faq/"
faq_url_external: false

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"

exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]

collections:
  about-us:
    output: true
  services:
    output: true
  funding-and-advisory:
    output: true
  retail-programmes:
    output: true
  digital-programmes:
    output: true
  media-centre:
    output: true
  professional-conversion-programme:
    output: true
  funding-and-support:
    output: true

resources_name: media-centre
